# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-26 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0017_auto_20220617_1635'),
        ('review', '0017_reviewassignment_display_public'),
    ]

    operations = [
    ]
