# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-26 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0053_display_article_images_settings'),
        ('journal', '0052_fixedpubcheckitems_select_open_reviews'),
        ('journal', '0053_issue_doi'),
        ('journal', '0054_auto_20220811_0958'),
    ]

    operations = [
    ]
