# Generated by Django 3.2.19 on 2023-08-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0060_alter_journal_code'),
    ]

    operations = [
    ]
