# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-26 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_auto_20220906_1107'),
        ('core', '0071_auto_20220616_1329'),
        ('core', '0074_auto_20220721_1448'),
    ]

    operations = [
    ]
