# Generated by Django 3.2.20 on 2024-02-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0073_bleach_title_20230523_1804'),
    ]

    operations = [
    ]
